# Generated by Django 3.2.3 on 2021-06-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('currentFitness', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('difficultyMultiplier', models.FloatField(null=True)),
                ('parts', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('timings', models.JSONField(blank=True)),
                ('user', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='run.user')),
                ('workout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='training', to='run.workout')),
            ],
        ),
    ]
