# Generated by Django 3.2.3 on 2021-06-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_auto_20210607_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='workouts',
            field=models.ManyToManyField(related_name='communities', to='run.WorkoutLog'),
        ),
        migrations.AlterField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(related_name='users', to='run.Community'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_run_user_friends_+', to='run.User'),
        ),
    ]
