# Generated by Django 3.2.3 on 2021-06-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_auto_20210607_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
