# Generated by Django 3.2.3 on 2021-06-07 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0009_auto_20210607_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='workouts',
        ),
    ]
