# Generated by Django 3.2.3 on 2021-06-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0013_auto_20210609_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
