# Generated by Django 3.2.3 on 2021-06-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0014_auto_20210609_0201'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='workoutlog',
            order_with_respect_to='datetime',
        ),
    ]
