# Generated by Django 3.2.3 on 2021-06-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0015_alter_workoutlog_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['datetime']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='workoutlog',
            order_with_respect_to=None,
        ),
    ]
