# Generated by Django 3.2.3 on 2021-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0016_auto_20210610_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'ordering': ['-datetime']},
        ),
    ]
