# Generated by Django 3.2.3 on 2021-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0017_alter_workoutlog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='workout',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='workout',
            field=models.ManyToManyField(blank=True, null=True, related_name='workoutlogs', to='run.Workout'),
        ),
    ]
