# Generated by Django 3.2.3 on 2021-06-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0018_auto_20210610_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='workout',
            new_name='workouts',
        ),
    ]
