# Generated by Django 3.2.3 on 2021-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0019_rename_workout_workoutlog_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
