# Generated by Django 3.2.3 on 2021-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0020_shopitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='workouts',
            field=models.ManyToManyField(blank=True, related_name='workoutlogs', to='run.Workout'),
        ),
    ]
