# Generated by Django 3.2.3 on 2021-06-09 21:43

from django.db import migrations, models
import run.models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0021_alter_workoutlog_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='default/default.jpg', upload_to=run.models.upload_to),
        ),
    ]
