# Generated by Django 3.2.3 on 2021-06-11 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0022_auto_20210610_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workoutlogs', related_query_name='workoutlogs', to='run.profile'),
        ),
    ]
