# Generated by Django 3.2.3 on 2021-06-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0025_auto_20210617_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='difficultyMultiplier',
            field=models.FloatField(null=True),
        ),
    ]
