# Generated by Django 3.2.3 on 2021-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0026_workout_difficultymultiplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='variation',
            new_name='measurement',
        ),
        migrations.AddField(
            model_name='workout',
            name='global_score',
            field=models.FloatField(null=True),
        ),
    ]
